### ISSUE TITLE
Overly-verbose pages

### ISSUE THREAD

**Issue by philsherry** [markwright785/A11YPatterns#20]
On a page such as "Form elements", there is a lot to get through before you reach the action (see #19 to fix that), but there are also a bunch of headings to sit through. These headings could be whittled down a bit. See screen shot for a clue. I've got video of VoiceOver reading through this page, which I'll upload somewhere. 

<img width="924" alt="headings" src="https://cloud.githubusercontent.com/assets/272769/24674748/8b7bd052-1974-11e7-8cec-5c8e0502c88a.png">

**Comment by philsherry** [comment]
As a suggestion, I'll add that the small navigation on that page could be below `main` in source order, and then sat over on the right of the page.

**Comment by philsherry** [comment]
Here's the award-winning video, as promised. I have no idea why VoiceOver whispers some items. 

https://www.dropbox.com/s/ltn5ago79xz5hq1/IMG_4265.m4v?dl=0

**Comment by markwright785** [comment]
changed contents list to match steven idea from slack 
"Checkboxes and radio buttons
Text inputs and textareas
Select menus (edited)"
