### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by philsherry** [markwright785/A11YPatterns#22]
You'll want to be paying some attention to link text. 

<img width="728" alt="links" src="https://cloud.githubusercontent.com/assets/272769/24676053/5ee2442c-1979-11e7-9747-5dacea10418b.png">

**Comment by stevenaproctor** [comment]
Definitely.

Relates to issue #4

**Comment by markwright785** [comment]
Changed links so it relates to pattern for example "View the text inputs and textareas CSS on GitHub"
